
Parameters:
  VpcName:
    Description: Name of VPC
    Type: String
  PublicSubName:
    Description: Public Subnet
    Type: String
  PrivateSubName:
    Description: Private Subnet
    Type: String 
  InstanceName:
    Description: Instance Name
    Type: String
  SecGroupName:
    Description: Sec Group Name
    Type: String 
Resources:
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "192.168.70.0/16"
      Tags:
        - Key: Name
          Value: !Ref VpcName
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-south-1" 
      VpcId: !Ref MyVPC
      CidrBlock: "192.168.70.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref PublicSubName
  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-south-1" 
      VpcId: !Ref MyVPC
      CidrBlock: "192.168.70.1/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Ref PrivateSubName
  LydiaSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "SSH and HTTP access"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
  
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0615bfdc319d617b1"
      InstanceType: "t2.micro"
      KeyName: "ec2-lydia"
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref LydiaSecurityGroup:
