AWSTemplateFormatVersion: 2010-09-09
Description: Creates a VPC with public and private subnets
Resources:
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "192.168.70.0/16"
      Tags:
        - Key: Name
          Value: VpcName
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-south-1a" 
      VpcId: MyVPC
      CidrBlock: "192.168.70.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubName
  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-south-1a" 
      VpcId: MyVPC
      CidrBlock: "192.168.70.1/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubName
  LydiaSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "SSH and HTTP access"
      VpcId: MyVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
  
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0615bfdc319d617b1"
      InstanceType: "t2.micro"
      KeyName: "ec2-lydia"
      SubnetId: PublicSubnet
      SecurityGroupIds:
        - !Ref LydiaSecurityGroup:
